# Generated by Django 5.0.4 on 2024-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_intercambios_valoradopostulante'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
