# Generated by Django 5.0.4 on 2024-05-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sucursal_address_alter_sucursal_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='es_empleado',
            field=models.BooleanField(default=False),
        ),
    ]
