# Generated by Django 5.0.4 on 2024-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_sucursal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Es_gerente',
            field=models.BooleanField(default=False),
        ),
    ]
