# Generated by Django 5.0.4 on 2024-05-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_es_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sucursal',
            field=models.OneToOneField(blank='', default='', on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to='myapp.sucursal'),
        ),
    ]
