# Generated by Django 5.0.4 on 2024-05-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_es_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
