# Generated by Django 5.0.4 on 2024-05-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sucursal_ciudad_alter_sucursal_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='ciudad',
        ),
    ]
