# Generated by Django 5.0.4 on 2024-05-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_sucursal_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='intercambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='myapp/static/fotos_intercambios')),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('modelo', models.CharField(default='', max_length=200)),
                ('marca', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
