# Generated by Django 5.0.4 on 2024-05-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_profile_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sucursal',
        ),
    ]
