# Generated by Django 5.0.4 on 2024-05-27 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_profile_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to='myapp.sucursal'),
        ),
    ]
