# Generated by Django 5.0.4 on 2024-05-29 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_intercambios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to='myapp.sucursal'),
        ),
    ]
