# Generated by Django 5.0.4 on 2024-06-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_intercambios_usuario_alter_profile_sucursal'),
        ('myapp', '0014_product_postulante_product_trueque_postulado'),
    ]

    operations = [
    ]
