# Generated by Django 5.0.4 on 2024-06-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_merge_20240602_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambios',
            name='sucursal_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios', to='myapp.sucursal'),
        ),
    ]
