# Generated by Django 5.0.4 on 2024-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_merge_20240602_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
