# Generated by Django 5.0.4 on 2024-06-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_intercambios_sucursal_asignada'),
        ('myapp', '0016_product_fecha_product_hora'),
    ]

    operations = [
    ]
