# Generated by Django 5.0.4 on 2024-06-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_intercambios_valorado_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambios',
            name='valorado',
        ),
    ]
