# Generated by Django 5.0.4 on 2024-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_rating_unique_together_alter_rating_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='cantValoraciones',
            field=models.IntegerField(default=1),
        ),
    ]
