# Generated by Django 5.0.4 on 2024-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_intercambios_valorado'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambios',
            name='valorado',
            field=models.BooleanField(default=False),
        ),
    ]
