# Generated by Django 5.0.4 on 2024-06-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_intercambios_valorado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercambios',
            old_name='valorado',
            new_name='valoradoEmpleado',
        ),
        migrations.AddField(
            model_name='intercambios',
            name='valoradoUsuario',
            field=models.BooleanField(default=False),
        ),
    ]
