# Generated by Django 5.0.4 on 2024-06-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_intercambios_fecha_intercambios_hora_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='intercambios',
            order_with_respect_to='fecha',
        ),
    ]
