# Generated by Django 5.0.4 on 2024-06-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_intercambios_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercambios',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='intercambios',
            order_with_respect_to=None,
        ),
    ]
