# Generated by Django 5.0.4 on 2024-06-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_intercambios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercambios',
            options={'ordering': ['fecha']},
        ),
    ]
