# Generated by Django 5.0.4 on 2024-06-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_intercambios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intercambios',
            options={'ordering': ['fecha', 'hora']},
        ),
    ]
