# Generated by Django 5.0.4 on 2024-05-27 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sucursal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal', to='myapp.sucursal'),
        ),
    ]
