# Generated by Django 5.0.4 on 2024-05-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_intercambios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambios',
            name='usuario',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='myapp.profile'),
        ),
    ]
