# Generated by Django 5.0.4 on 2024-05-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='postulante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to='myapp.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='trueque_postulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.intercambios'),
        ),
    ]
